/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;

/**
 *
 * @author flores
 */
public class Asientos extends javax.swing.JDialog implements ActionListener {
    
    private JButton[] asientos = new JButton[25];
    private List<Integer> lista = new ArrayList<>();
    private int[] click = new int[25] ;
       
    private File file = new File("listaAsientos.txt");
        
        
    
    /**
     * Creates new form Asientos
     */
    public Asientos(java.awt.Frame parent, boolean modal){
        super(parent, modal);
        initComponents();
        
        GridLayout gl = new GridLayout();
        this.setLayout(gl);
        gl.setColumns(5);
        gl.setRows(5);
        gl.setHgap(5);
        gl.setVgap(5);
        for(int i = 0; i < asientos.length; i++){
            asientos[i] = new JButton("S: " + (i+1));
            asientos[i].addActionListener(this);
            this.add(asientos[i]);
        }
    }
    
    public List<Integer> getLista(){
        return lista;
    }
    
   @Override
    public void actionPerformed(ActionEvent e) {    
        Object llave = e.getSource();
    
        if(!file.exists()){
           try{
            file.createNewFile();
           }catch(IOException ex){
               ex.printStackTrace();
           }
        }
    
        
        for(int i=0; i < asientos.length; i++){
            if(llave.equals(asientos[i]) ){
                asientos[i].setBackground(Color.RED);
                lista.add((i+1));
                click[i]++;
            }else if(click[i] > 2){
                click[i] = 0;
            }
        }
        
        for(int i=0; i < asientos.length; i++){
            if(llave.equals(asientos[i]) ){
                switch(click[i]){
                    case 1:
                        asientos[i].setEnabled(false);
                        asientos[i].setBackground(Color.RED);
                        break;
                    case 2:
                        asientos[i].setBackground(null);
                        break;

                    default:
                        asientos[i].setBackground(null);
                        break;
                }
            }
            
        }
 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Lista Asientos"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Asientos dialog = new Asientos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
